src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BlogRepository::class)]
class Blog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'blogs')]
    private ?User $author = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $publication_date = null;

    #[ORM\Column]
    private ?bool $is_published = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $featured_image = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\ManyToMany(targetEntity: BlogCategory::class, mappedBy: 'blog')]
    private Collection $blogCategories;

    public function __toString(): string
    {
        return (string) $this->title;
    }
    
    public function __construct()
    {
        $this->blogCategories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeImmutable
    {
        return $this->publication_date;
    }

    public function setPublicationDate(?\DateTimeImmutable $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function isIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(?bool $is_published): static
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(?string $featured_image): static
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    /**
     * @return Collection<int, BlogCategory>
     */
    public function getBlogCategories(): Collection
    {
        return $this->blogCategories;
    }

    public function addBlogCategory(BlogCategory $blogCategory): static
    {
        if (!$this->blogCategories->contains($blogCategory)) {
            $this->blogCategories->add($blogCategory);
            $blogCategory->addBlog($this);
        }

        return $this;
    }

    public function removeBlogCategory(BlogCategory $blogCategory): static
    {
        if ($this->blogCategories->removeElement($blogCategory)) {
            $blogCategory->removeBlog($this);
        }

        return $this;
    }
}

src/Entity/Content.php
<?php

namespace App\Entity;

use App\Repository\ContentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContentRepository::class)]
class Content
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content_text = null;

    public function __toString(): string
    {
        return (string) $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getContentText(): ?string
    {
        return $this->content_text;
    }

    public function setContentText(?string $content_text): static
    {
        $this->content_text = $content_text;

        return $this;
    }
}

src/Entity/Page.php
<?php

namespace App\Entity;

use App\Repository\PageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PageRepository::class)]
class Page
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $heading = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $featured_image = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $page_content = null;

    #[ORM\Column(nullable: true)]
    private ?bool $content_first = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_service = null;

    #[ORM\ManyToMany(targetEntity: Section::class, inversedBy: 'pages')]
    private Collection $sections;

    public function __toString(): string
    {
        return (string) $this->heading;
    }

    public function __construct()
    {
        $this->sections = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(?string $heading): static
    {
        $this->heading = $heading;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(?string $featured_image): static
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function getPageContent(): ?string
    {
        return $this->page_content;
    }

    public function setPageContent(?string $page_content): static
    {
        $this->page_content = $page_content;

        return $this;
    }

    public function isContentFirst(): ?bool
    {
        return $this->content_first;
    }

    public function setContentFirst(?bool $content_first): static
    {
        $this->content_first = $content_first;

        return $this;
    }

    public function isIsService(): ?bool
    {
        return $this->is_service;
    }

    public function setIsService(?bool $is_service): static
    {
        $this->is_service = $is_service;

        return $this;
    }

    /**
     * @return Collection<int, Section>
     */
    public function getSections(): Collection
    {
        return $this->sections;
    }

    public function addSection(Section $section): static
    {
        if (!$this->sections->contains($section)) {
            $this->sections->add($section);
        }

        return $this;
    }

    public function removeSection(Section $section): static
    {
        $this->sections->removeElement($section);

        return $this;
    }
}

src/Entity/SEO.php
<?php

namespace App\Entity;

use App\Repository\SEORepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SEORepository::class)]
class SEO
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $heading = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo_path = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $keywords = null;

    public function __toString(): string
    {
        return (string) $this->heading;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(?string $heading): static
    {
        $this->heading = $heading;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getLogoPath(): ?string
    {
        return $this->logo_path;
    }

    public function setLogoPath(?string $logo_path): static
    {
        $this->logo_path = $logo_path;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): static
    {
        $this->keywords = $keywords;

        return $this;
    }
}

src/Entity/Section.php
<?php

namespace App\Entity;

use App\Repository\SectionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SectionRepository::class)]
class Section
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $template_path = null;

    #[ORM\Column(nullable: true)]
    private ?int $priority = null;

    #[ORM\ManyToMany(targetEntity: Page::class, mappedBy: 'sections')]
    private Collection $pages;

    public function __construct()
    {
        $this->pages = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->description;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getTemplatePath(): ?string
    {
        return $this->template_path;
    }

    public function setTemplatePath(?string $template_path): static
    {
        $this->template_path = $template_path;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(?int $priority): static
    {
        $this->priority = $priority;

        return $this;
    }

    /**
     * @return Collection<int, Page>
     */
    public function getPages(): Collection
    {
        return $this->pages;
    }

    public function addPage(Page $page): static
    {
        if (!$this->pages->contains($page)) {
            $this->pages->add($page);
            $page->addSection($this);
        }

        return $this;
    }

    public function removePage(Page $page): static
    {
        if ($this->pages->removeElement($page)) {
            $page->removeSection($this);
        }

        return $this;
    }
}

templates/sections/about.html.twig
	<!-- About Area Start -->
	<div class="about-area section-padding">
		<div class="bounce-top shape2">
			<img src="{{ asset('site/assets/img/shape/ab-shape-3.png') }}" alt="">
		</div>
		<div class="item-roll shape1">
			<img src="{{ asset('site/assets/img/shape/ab-shape-2.png') }}" alt="">
		</div>
		<div class="container">
			<div class="row">
				<div class="col-xl-6 col-lg-6 md-mb-35">
					<div class="about-left">
						<div class="about-img">
							<img src="{{ asset('site/web_images/' ~ images['about-us'].src ) }}" alt="">
						</div>
						<div class="item-bounce about-shape">
							<img src="{{ asset('site/assets/img/shape/ab-shape-1.png') }}" alt="">
						</div>
					</div>
				</div>
				<div class="col-xl-6 col-lg-6">
					<div class="s-table">
						<div class="s-tablec">
							<div class="section-title section-title-right"> <span class="section-top">//  About Us</span>
								<h2>{{ content['about-us-heading'].contentText}}</h2>
								<p class="pt-30 pb-35">{{ content['about-us-text'].contentText}}</p>
								<div class="about-buttom d-sm-flex">
									<div class="about-btn"> <a class="attoyer-btn all-btn mr-100" href="#">{{ content['about-us-action'].contentText}}</a>
									</div>
									<div class="about-signa">
										{# <img src="{{ asset('site/assets/img/signature.png') }}" alt=""> #}
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- About Area End -->

templates/sections/blog_article.html.twig
	<!-- Blog Details Start -->
	<div class="blog-details section-padding">
		<div class="container">
			<div class="row">
				<div class="col-xl-8 col-lg-8 md-mb-30">
					<div class="blog-item mb-50">
						<div class="blog-img">
							<img src="{{ asset('site/images/blog_images/' ~ blog_post.featuredImage ) }}" alt="">
						</div>
						<div class="blog-content">
							<h3><a href="#">{{blog_post.title}}</a></h3>
							<ul class="pt-10 pb-20">
								<li><i class="flaticon-user"></i> Posted by <a href="#">{{blog_post.author}}</a>
								</li>
								<li><i class="flaticon-date"></i> {{blog_post.publicationDate|date('d, M Y')}}</li>
								<li><i class="flaticon-comment"></i> 
                                {% for category in blog_post.blogCategories %}
                                    {{ category }}
                                    {% if not loop.last %}, {% endif %}
                                {% endfor %}
                                </li>
							</ul>
							{{blog_post.content|raw}}
                        </div>
					</div>
					<div class="blog-related">
						<div class="row align-items-center">
							<div class="col-md-7">
								<div class="related-tag">	<span>Related Tags:</span> 
									<ul>
										<li><a href="#">#Law</a>
										</li>
										<li><a href="#">#Family Law</a>
										</li>
										<li><a href="#">#Corporate Law</a>
										</li>
									</ul>
								</div>
							</div>
							<div class="col-md-5">
								<div class="related-share">
									<ul>
										<li><a href="#"><i class="flaticon-facebook-app-symbol"></i></a>
										</li>
										<li><a href="#"><i class="flaticon-twitter"></i></a>
										</li>
										<li><a href="#"><i class="flaticon-instagram"></i></a>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					{# <div class="row">
						<div class="col-lg-12">
							<div class="comment-count">
								<h3>03 Comments</h3>
							</div>
							<div class="comment-temp">
								<ul>
									<li>
										<div class="comment-item">
											<div class="comt-user">
												<img src="assets/img/author.jpg" alt="">
											</div>
											<div class="comt-detail">
												<div class="comtuser-name">
													<h3>Mithila Islam</h3>
													<p>25 June, 21</p>	<a class="comt-reply" href="#"><i class="flaticon-reply"></i> Reply</a>
												</div>
												<p>Proactively envisioned multimedia based expertise and cross-media growth strategies. Seamlessly ize quality intellectual capital without superior collaboration and sharing. Holistically pontificate installed.</p>
											</div>
										</div>
									</li>
									<li class="comt-sub">
										<div class="comment-item">
											<div class="comt-user">
												<img src="assets/img/author2.jpg" alt="">
											</div>
											<div class="comt-detail">
												<div class="comtuser-name">
													<h3>Tahmina Anny</h3>
													<p>27 June, 21</p>	<a class="comt-reply" href="#"><i class="flaticon-reply"></i> Reply</a>
												</div>
												<p>Proactively envisioned multimedia based expertise and cross-media growth strategies. Seamlessly ize quality intellectual capital.</p>
											</div>
										</div>
									</li>
									<li>
										<div class="comment-item mb-25">
											<div class="comt-user">
												<img src="assets/img/author3.jpg" alt="">
											</div>
											<div class="comt-detail">
												<div class="comtuser-name">
													<h3>Mark Parker</h3>
													<p>30 June, 21</p>	<a class="comt-reply" href="#"><i class="flaticon-reply"></i> Reply</a>
												</div>
												<p>Proactively envisioned multimedia based expertise and cross-media growth strategies. Seamlessly ize quality intellectual capital without superior collaboration and sharing. Holistically pontificate installed.</p>
											</div>
										</div>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<div class="comment-form-title">
								<h3>Write Your Comment</h3>
							</div>
							<div class="comment-form">
								<form class="form" action="#">
									<div class="row">
										<div class="col-lg-6">
											<div class="form-group">
												<input type="text" name="name" placeholder="Name" required="required">
											</div>
										</div>
										<div class="col-lg-6">
											<div class="form-group">
												<input type="email" name="email" placeholder="Email" required="required">
											</div>
										</div>
										<div class="col-lg-6">
											<div class="form-group">
												<input type="text" name="website" placeholder="Website Name" required="required">
											</div>
										</div>
										<div class="col-lg-6">
											<div class="form-group">
												<input type="text" name="phone" placeholder="Phone Number (Optional)" required="required">
											</div>
										</div>
										<div class="col-lg-12">
											<div class="form-group">
												<textarea name="message" rows="6" placeholder="Your Comment"></textarea>
											</div>
										</div>
										<div class="col-lg-12">
											<button type="submit" class="attoyer-btn all-btn">Send Massage</button>											
										</div>
									</div>
								</form>
							</div>
						</div>
					</div> #}
				</div>
				<div class="col-lg-4">
					<div class="sidebar">
						<div class="side-search side-widget">
							<form class="side-search-box" action="#">
								<input class="form-control" placeholder="Search Now..." type="text">
								<button type="submit" class="search-button"><i class="flaticon-search"></i>
								</button>
							</form>
						</div>
						<div class="side-widget about-me">
							<h3>About Me</h3>
							<img src="assets/img/about-me.jpg" alt="">	<b>{{blog_post.author}}</b>
							<p>{{blog_post.author.about}}</p>
						</div>
						<div class="side-widget blog-cat">
							<h3>Blog Catagories</h3>
							<div class="cat-list">
								<ul>
                                    {% for category in blog_post.blogCategories %}
                                        <li>
                                            <a href="#">{{ category }}</a>
                                        </li>
                                    {% endfor %}									
								</ul>
							</div>
						</div>
						{# <div class="side-widget">
							<h3>Follow Us</h3>
							<div class="follow-social">
								<ul>
									<li><a href="#"><i class="flaticon-facebook-app-symbol"></i></a>
									</li>
									<li><a href="#"><i class="flaticon-twitter"></i></a>
									</li>
									<li><a href="#"><i class="flaticon-linkedin"></i></a>
									</li>
									<li><a href="#"><i class="flaticon-vimeo"></i></a>
									</li>
								</ul>
							</div>
						</div>
						<div class="side-widget">
							<h3>Archive Posts</h3>	
							<div class="blog-archive">
								<ul>
									<li><a href="#"><i class="flaticon-folder"></i> April 2015</a>
									</li>
									<li><a href="#"><i class="flaticon-folder"></i> December 2016</a>
									</li>
									<li><a href="#"><i class="flaticon-folder"></i> September 2017</a>
									</li>
									<li><a href="#"><i class="flaticon-folder"></i> November 2018</a>
									</li>
									<li><a href="#"><i class="flaticon-folder"></i> March 2019</a>
									</li>
									<li><a href="#"><i class="flaticon-folder"></i> January 2020</a>
									</li>
									<li><a href="#"><i class="flaticon-folder"></i> August 2021</a>
									</li>
								</ul>
							</div>
						</div>
						<div class="side-widget bg-newsletter">
							<h3>Get Regular Updates</h3>	
							<div class="newsletter">
								<form class="form" action="#">
									<input type="text" name="name" placeholder="Enter Name">
									<input type="email" name="name" placeholder="Enter Email">
									<button type="submit">Get Newsletter</button>
								</form>
							</div>
						</div>
						<div class="side-widget">
							<h3>Popular Tags</h3>	
							<div class="blog-tags">
								<ul>
									<li><a href="#">Finance</a>
									</li>
									<li><a href="#">tech</a>
									</li>
									<li><a href="#">life</a>
									</li>
									<li><a href="#">life</a>
									</li>
									<li><a href="#">tech</a>
									</li>
									<li><a href="#">inance</a>
									</li>
									<li><a href="#">life</a>
									</li>
									<li><a href="#">Finance</a>
									</li>
									<li><a href="#">tech</a>
									</li>
								</ul>
							</div>
						</div> #}
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Blog Single End -->

templates/sections/blog_posts.html.twig
	<!-- Blog Area Start -->
	<div class="blog-area section-padding">
		<div class="container">
			<div class="row">
				<div class="col-xl-12 col-lg-12">
					<div class="section-title">	<span class="section-top">//  News & Blog</span>
						<h2>Tips From Kimotho Githinji & Advocates</h2>
					</div>
				</div>
			</div>
			<div class="row">
              {% for blog_post in blog_posts %}
				<div class="col-xl-4 col-lg-4 col-md-6 md-mb-30">
					<div class="blog-item">
						<div class="blog-img">
							<img src="{{ asset('site/images/blog_images/' ~ blog_post.featuredImage ) }}" alt="">
						</div>
						<div class="blog-content">
							<ul>
								<li><i class="flaticon-date"></i> {{blog_post.publicationDate|date('d, M Y') }}</li>
								<li><i class="flaticon-comment"></i> 
                                {% for category in blog_post.blogCategories %}
                                    {{ category }}
                                    {% if not loop.last %}, {% endif %}
                                {% endfor %}
                                </li>
							</ul>
							<h3><a href="{{path('blog_detail', {'slug': blog_post.slug })}}">{{blog_post.title|title}}</a></h3>
							<a href="#">Read Article <i class="flaticon-right-arrow"></i></a>
						</div>
					</div>
				</div>
              {% endfor %}
			</div>
		</div>
	</div>
	<!-- Blog Area End -->

templates/sections/service.html.twig
	{# page for a particular sevice #}
    <!-- Blog Details Start -->
	<div class="blog-details section-padding">
		<div class="container">
			<div class="row">
				<div class="col-xl-8 col-lg-8 md-mb-30">
					<div class="blog-item mb-50">
						<div class="blog-img">
							<img src="{{asset('site/images/page_images/' ~ page.featuredImage ) }}" alt="">
						</div>
						<div class="blog-content">
							<h2><a href="#">{{page.metaTitle}}</a></h2>
							{{page.pageContent|raw}}
						</div>
					</div>
					<div class="blog-related">
						<div class="row align-items-center">
							<div class="col-md-7">
								<div class="related-tag">	<span>Related Services:</span> 
									<ul>
                                      {% for service in services %}
										<li><a href="{{path('app_service', {'service': service.url})}}">#{{service.heading}}</a>
										</li>
                                      {% endfor %}
									</ul>
								</div>
							</div>
							<div class="col-md-5">
								<div class="related-share">
									<ul>
										<li><a href="#"><i class="flaticon-facebook-app-symbol"></i></a>
										</li>
										<li><a href="#"><i class="flaticon-twitter"></i></a>
										</li>
										<li><a href="#"><i class="flaticon-instagram"></i></a>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="sidebar">
						<div class="side-search side-widget">
							<form class="side-search-box" action="#">
								<input class="form-control" placeholder="Search Now..." type="text">
								<button type="submit" class="search-button"><i class="flaticon-search"></i>
								</button>
							</form>
						</div>
						<div class="side-widget about-me">
							<h3>About Us</h3>
							<img src="{{asset('site/images/' ~ global_vars('seo').logoPath )}}" alt="">	<b>{{ content['company-name'].contentText}}</b>
							<p>{{ content['about-us-text'].contentText}}</p>
						</div>
						{# <div class="side-widget blog-cat">
							<h3>Blog Catagories</h3>
							<div class="cat-list">
								<ul>
									<li><a href="#">Construction<span>09</span></a>
									</li>
									<li><a href="#">Finance<span>41</span></a>
									</li>
									<li><a href="#">Interior Design<span>05</span></a>
									</li>
									<li><a href="#">Business Managment<span>94</span></a>
									</li>
									<li><a href="#">User Research<span>23</span></a>
									</li>
								</ul>
							</div>
						</div> #}
						{# <div class="side-widget">
							<h3>Follow Us</h3>
							<div class="follow-social">
								<ul>
									<li><a href="#"><i class="flaticon-facebook-app-symbol"></i></a>
									</li>
									<li><a href="#"><i class="flaticon-twitter"></i></a>
									</li>
									<li><a href="#"><i class="flaticon-linkedin"></i></a>
									</li>
									<li><a href="#"><i class="flaticon-vimeo"></i></a>
									</li>
								</ul>
							</div>
						</div> #}
						{# <div class="side-widget">
							<h3>Archive Posts</h3>	
							<div class="blog-archive">
								<ul>
									<li><a href="#"><i class="flaticon-folder"></i> April 2015</a>
									</li>
									<li><a href="#"><i class="flaticon-folder"></i> December 2016</a>
									</li>
									<li><a href="#"><i class="flaticon-folder"></i> September 2017</a>
									</li>
									<li><a href="#"><i class="flaticon-folder"></i> November 2018</a>
									</li>
									<li><a href="#"><i class="flaticon-folder"></i> March 2019</a>
									</li>
									<li><a href="#"><i class="flaticon-folder"></i> January 2020</a>
									</li>
									<li><a href="#"><i class="flaticon-folder"></i> August 2021</a>
									</li>
								</ul>
							</div>
						</div> #}
						{# <div class="side-widget bg-newsletter">
							<h3>Get Regular Updates</h3>	
							<div class="newsletter">
								<form class="form" action="#">
									<input type="text" name="name" placeholder="Enter Name">
									<input type="email" name="name" placeholder="Enter Email">
									<button type="submit">Get Newsletter</button>
								</form>
							</div>
						</div> #}
						{# <div class="side-widget">
							<h3>Popular Tags</h3>	
							<div class="blog-tags">
								<ul>
									<li><a href="#">Finance</a>
									</li>
									<li><a href="#">tech</a>
									</li>
									<li><a href="#">life</a>
									</li>
									<li><a href="#">life</a>
									</li>
									<li><a href="#">tech</a>
									</li>
									<li><a href="#">inance</a>
									</li>
									<li><a href="#">life</a>
									</li>
									<li><a href="#">Finance</a>
									</li>
									<li><a href="#">tech</a>
									</li>
								</ul>
							</div>
						</div> #}
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Blog Single End -->

templates/sections/services_pg_list.html.twig
	<!-- Services Area Start -->
	<div class="services-area section-padding">
		<div class="container">
			<div class="row align-items-center">
                {% for service in services %}
                    <div class="col-xl-4 col-lg-4 col-md-6 mb-30">
                        <div class="services-tiem">
                            <div class="services-img">
                                <img src="{{ asset('site/images/page_images/' ~ service.featuredImage ) }}" alt="{{service.heading}}">
                            </div>
                            <div class="services-content">
                                <a href="{{path('app_service', {'service': service.url })}}"><h3 class="pt-20">{{service.heading}}</h3></a>
                                <p class="pb-10 pt-10">{{service.metaDescription}}</p> 
                                <a href="{{path('app_service', {'service': service.url })}}">Read More <i class="flaticon-right-arrow"></i></a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
			</div>
		</div>
	</div>
	<!-- Services Area End -->